# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for MovieDemo

pod 'Alamofire'
pod 'PageMenu'
pod 'Cosmos', '~> 11.0'
pod 'FSPagerView', '~> 0.7.1'
pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
pod 'SDWebImage'
pod 'FMDB'
pod 'RxSwift', '~> 3.0'
pod 'RxCocoa', '~> 3.0'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.3'
      end
    end
  end
  
end
